repos:
  - repo: local
    hooks:
      # ToDo:
      # - Find out how to stop subsequent steps in the pipeline running if a prior step fails...
      # - Integrate linters e.g. Black into the pipeline

      # ToDo: Find out why the sort-imports hook is not working, and fix.
      #- id: sort-imports
      #  name: Sort imports with isort
      #  entry: poetry run isort .
      #  language: system
      #  types: [python]
      #  pass_filenames: false
      #  always_run: true
      #  stages: [commit]
      - id: update-lock
        name: Update poetry lock
        entry: poetry lock
        language: system
        types: [python]
        pass_filenames: false
        always_run: true 
        stages: [commit]
      - id: add-updated-lock-file
        name: Add the updated file to git
        entry: git add ./poetry.lock
        language: system
        types: [python]
        pass_filenames: false
        always_run: true 
        stages: [commit]
      - id: install-dependencies
        name: Install dependencies with poetry
        entry: poetry install
        language: system
        types: [python]
        pass_filenames: false
        always_run: true #find out what happens when this is false
        stages: [commit]
      - id: pytest
        name: Run Pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true #find out what happens when this is false
        stages: [commit]