repos:
  - repo: local
    hooks:
      # find out how to stop subsequent steps in the pipeline running if a prior step fails...
      - id: install-dependencies
        name: Install dependencies with poetry
        entry: poetry install
        language: system
        types: [python]
        pass_filenames: false
        always_run: true #find out what happens when this is false
        stages: [commit]
      - id: pytest
        name: Run Pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true #find out what happens when this is false
        stages: [commit]