trigger:
  branches:
    include:
    - main

variables:
  # Deploy to prod infra if the branch is a prod-release tag.
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/prod-release-') }}:
    subscriptionId: 'PLACEHOLDER'
    resourceGroup: 'PLACEHOLDER'
    environment: 'prod'
  # Otherwise, deploy to dev infra.
  ${{ else }}:
    subscriptionId: 'a3c531dd-409f-4d4a-b076-0e2020958b66'
    resourceGroup: 'Threat-Intelligence-Automation'
    environment: 'dev'
  

pool:
  vmImage: 'ubuntu-latest'

# ToDo: Make this whole step conditional on whether changes have taken place in /infra (excluding .md files).
# ToDo: Also make manual validation checks in prod before the command is used with the --deploy flag. In prod, don't want any infra changes to take place without a person's manual approval - so make the prod environment require that step (might need to create a new step with what-if etc in the pipeline, just for prod, for this approval, and take it out the main script...)
steps:
- script: |
    ./infra/provision-infra.sh \
      --subscription-id "$(subscriptionId)" \
      --resource-group "$(resourceGroup)" \
      --target-deployment-environment "$(environment)"
  displayName: 'Provision Infrastructure'

# Next steps:
# - Deploy the actual code and applications.