trigger:
  branches:
    include:
    - main

variables:
  # Deploy to prod infra if the branch is a prod-release tag.
  # ToDo: Discuss this strategy with Mike. Is this the best way to do it?
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/prod-release-') }}:
    targetDeployment: 'prod'
  # Otherwise, deploy to dev infra.
  ${{ else }}:
    targetDeployment: 'dev'
  

jobs:
  # Job 1: Run unit tests on Windows, since they require a CosmosDB emulator, which is only available on Windows.
  # ToDo: Make everything stop if unit tests fail
  - job: UnitTests
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: |
        echo "Running unit tests on Windows"
        # Add your commands for unit testing here

  # Job 2: Apply configurations to infra using bicep. Most of infra already provisioned through the base platform.
  - job: ProvisionCustomInfra
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Applying configurations to infra using bicep"
        # Add your commands for applying configurations here

  # Job 3: Deploy to correct environment, calculated in the variables section.
  - job: Deployment
    dependsOn:
    - UnitTests
    - ProvisionCustomInfra
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "Deployment steps on Linux"
        # Add your commands for deployment here