# Base stage for common setup
FROM python:3.10.8 as base
WORKDIR /usr/src/app

# Copy the base requirements and install
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Production stage
FROM base as production
# Ensure Python outputs all logs to the terminal without buffering
ENV PYTHONUNBUFFERED=1
COPY . /usr/src/app
CMD ["python", "./ingestion_pipeline.py"]

# Development/Testing stage
FROM base as development
ENV PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir pytest
COPY . /usr/src/app
# Command to run tests; adjust the path to test scripts as needed
CMD pytest && python ./ingestion_pipeline.py
